local addonName, addon = ...
local DungeonQuestTracker = addon

-- Quest data for all Classic and TBC dungeons
-- Structure: Complex > Dungeon > Quest
-- faction: "Alliance", "Horde", or "Both"
-- heroic: true if quest requires heroic mode
-- prerequisites: list of prerequisite quest IDs with names
--
-- Generated by tools/scrape_quests.py from Wowhead TBC Classic data

DungeonQuestTracker.DUNGEON_DATA = {

    -- ========================================================================
    -- CLASSIC DUNGEONS
    -- ========================================================================

    -- Ragefire Chasm
    {
        complex = "Ragefire Chasm",
        dungeons = {
            {
                name = "Ragefire Chasm",
                levelRange = "13-18",
                quests = {
                    {
                        questId = 5725,
                        name = "The Power to Destroy...",
                        description = "Spells of Shadow, Incantations from the Nether",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 5723,
                        name = "Testing an Enemy's Strength",
                        description = "Ragefire Trogg x 8, Ragefire Shaman x 8",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 5761,
                        name = "Slaying the Beast",
                        description = "Taragaman the Hungerer's Heart",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 5722,
                        name = "Searching for the Lost Satchel",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 5724,
                        name = "Returning the Lost Satchel",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {
                            { questId = 5722, name = "Searching for the Lost Satchel" },
                        },
                    },
                    {
                        questId = 5728,
                        name = "Hidden Enemies",
                        description = "Bazzalan, Jergosh the Invoker",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
        },
    },

    -- Wailing Caverns
    {
        complex = "Wailing Caverns",
        dungeons = {
            {
                name = "Wailing Caverns",
                levelRange = "17-24",
                quests = {
                    {
                        questId = 1486,
                        name = "Deviate Hides",
                        description = "Deviate Hide x 20",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 1487,
                        name = "Deviate Eradication",
                        description = "Deviate Ravager x 7, Deviate Viper x 7, Deviate Shambler x 7, Deviate Dreadfang x 7",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 959,
                        name = "Trouble at the Docks",
                        description = "99-Year-Old Port",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 962,
                        name = "Serpentbloom",
                        description = "Serpentbloom x 10",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 914,
                        name = "Leaders of the Fang",
                        description = "Gem of Cobrahn, Gem of Anacondra, Gem of Pythas, Gem of Serpentis",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 6981,
                        name = "The Glowing Shard",
                        description = "Then, deliver the shard as you are directed. Requirements:, Speak with someone in Ratchet about the Glowing Shard",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
        },
    },

    -- The Deadmines
    {
        complex = "The Deadmines",
        dungeons = {
            {
                name = "The Deadmines",
                levelRange = "17-26",
                quests = {
                    {
                        questId = 155,
                        name = "The Defias Brotherhood",
                        description = "Escort The Defias Traitor to discover where VanCleef is hiding",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 214,
                        name = "Red Silk Bandanas",
                        description = "Red Silk Bandana x 10",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 168,
                        name = "Collecting Memories",
                        description = "Miners' Union Card x 4",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 167,
                        name = "Oh Brother. . .",
                        description = "Thistlenettle's Badge",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 2040,
                        name = "Underground Assault",
                        description = "Gnoam Sprecklesprocket",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
        },
    },

    -- Shadowfang Keep
    {
        complex = "Shadowfang Keep",
        dungeons = {
            {
                name = "Shadowfang Keep",
                levelRange = "22-30",
                quests = {
                    {
                        questId = 1098,
                        name = "Deathstalkers in Shadowfang",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 1013,
                        name = "The Book of Ur",
                        description = "The Book of Ur",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 1014,
                        name = "Arugal Must Die",
                        description = "Head of Arugal",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 1740,
                        name = "The Orb of Soran'ruk",
                        description = "Soran'ruk Fragment x 3, Large Soran'ruk Fragment",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
        },
    },

    -- Blackfathom Deeps
    {
        complex = "Blackfathom Deeps",
        dungeons = {
            {
                name = "Blackfathom Deeps",
                levelRange = "24-32",
                quests = {
                    {
                        questId = 1275,
                        name = "Researching the Corruption",
                        description = "Corrupted Brain Stem x 8",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 1198,
                        name = "In Search of Thaelrid",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 1200,
                        name = "Blackfathom Villainy",
                        description = "Head of Kelris",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {
                            { questId = 1198, name = "In Search of Thaelrid" },
                        },
                    },
                    {
                        questId = 6564,
                        name = "Allegiance to the Old Gods",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 6563,
                        name = "The Essence of Aku'Mai",
                        description = "Sapphire of Aku'Mai x 20",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
        },
    },

    -- The Stockade
    {
        complex = "The Stockade",
        dungeons = {
            {
                name = "The Stockade",
                levelRange = "24-32",
                quests = {
                    {
                        questId = 377,
                        name = "Crime and Punishment",
                        description = "Hand of Dextren Ward",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 378,
                        name = "The Fury Runs Deep",
                        description = "Head of Deepfury",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 387,
                        name = "Quell The Uprising",
                        description = "Defias Prisoner x 10, Defias Convict x 8, Defias Insurgent x 8",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 386,
                        name = "What Comes Around...",
                        description = "Head of Targorr",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 388,
                        name = "The Color of Blood",
                        description = "Red Wool Bandana x 10",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
        },
    },

    -- Gnomeregan
    {
        complex = "Gnomeregan",
        dungeons = {
            {
                name = "Gnomeregan",
                levelRange = "29-38",
                quests = {
                    {
                        questId = 2904,
                        name = "A Fine Mess",
                        description = "Kernobee Rescue",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 2926,
                        name = "Gnogaine",
                        description = "Full Leaden Collection Phial",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 2962,
                        name = "The Only Cure is More Green Glow",
                        description = "Ozzie will also require your Heavy Leaden Collection Phial when the task is complete. Requirements:, High Potency Radioactive Fallout",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 2930,
                        name = "Data Rescue",
                        description = "Prismatic Punch Card",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 2924,
                        name = "Essential Artificials",
                        description = "Essential Artificial x 12",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 2928,
                        name = "Gyrodrillmatic Excavationators",
                        description = "Robo-mechanical Guts x 24",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
        },
    },

    -- Scarlet Monastery
    {
        complex = "Scarlet Monastery",
        dungeons = {
            {
                name = "SM: Graveyard",
                levelRange = "28-38",
                quests = {
                    {
                        questId = 1051,
                        name = "Vorrel's Revenge",
                        description = "Vorrel's Wedding Ring",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 1113,
                        name = "Hearts of Zeal",
                        description = "Heart of Zeal x 20",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
            {
                name = "SM: Library",
                levelRange = "29-39",
                quests = {
                    {
                        questId = 1050,
                        name = "Mythology of the Titans",
                        description = "Mythology of the Titans",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 1049,
                        name = "Compendium of the Fallen",
                        description = "Compendium of the Fallen",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 1951,
                        name = "Rituals of Power",
                        description = "Rituals of Power",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
            {
                name = "SM: Armory + Cathedral",
                levelRange = "32-45",
                quests = {
                    {
                        questId = 1053,
                        name = "In the Name of the Light",
                        description = "High Inquisitor Whitemane, Scarlet Commander Mograine, Herod, Houndmaster Loksey",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
        },
    },

    -- Razorfen Kraul
    {
        complex = "Razorfen Kraul",
        dungeons = {
            {
                name = "Razorfen Kraul",
                levelRange = "30-40",
                quests = {
                    {
                        questId = 1221,
                        name = "Blueleaf Tubers",
                        description = "Grab a Snufflenose Command Stick. Grab and read the Snufflenose Owner's Manual. In Razorfen Kraul, use the Crate with Holes to summon a Snufflenose...",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 1144,
                        name = "Willix the Importer",
                        description = "Help Willix the Importer escape from Razorfen Kraul",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 1101,
                        name = "The Crone of the Kraul",
                        description = "Razorflank's Medallion",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 1142,
                        name = "Mortality Wanes",
                        description = "Treshala's Pendant",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
        },
    },

    -- Razorfen Downs
    {
        complex = "Razorfen Downs",
        dungeons = {
            {
                name = "Razorfen Downs",
                levelRange = "37-46",
                quests = {
                    {
                        questId = 3341,
                        name = "Bring the End",
                        description = "Skull of the Coldbringer",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 3636,
                        name = "Bring the Light",
                        description = "Amnennar the Coldbringer",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 6626,
                        name = "A Host of Evil",
                        description = "Razorfen Battleguard x 8, Razorfen Thornweaver x 8, Death's Head Cultist x 8",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 3523,
                        name = "Scourge of the Downs",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 6522,
                        name = "An Unholy Alliance",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
        },
    },

    -- Uldaman
    {
        complex = "Uldaman",
        dungeons = {
            {
                name = "Uldaman",
                levelRange = "41-51",
                quests = {
                    {
                        questId = 2398,
                        name = "The Lost Dwarves",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 2418,
                        name = "Power Stones",
                        description = "Dentrium Power Stone x 8, An'Alleum Power Stone x 8",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 704,
                        name = "Agmond's Fate",
                        description = "Carved Stone Urn x 4",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 17,
                        name = "Uldaman Reagent Run",
                        description = "Magenta Fungus Cap x 12",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 2278,
                        name = "The Platinum Discs",
                        description = "Learn what lore that the stone watcher has to offer",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 2198,
                        name = "The Shattered Necklace",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
        },
    },

    -- Zul'Farrak
    {
        complex = "Zul'Farrak",
        dungeons = {
            {
                name = "Zul'Farrak",
                levelRange = "44-54",
                quests = {
                    {
                        questId = 2768,
                        name = "Divino-matic Rod",
                        description = "Divino-matic Rod",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 3042,
                        name = "Troll Temper",
                        description = "Troll Temper x 20",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 2865,
                        name = "Scarab Shells",
                        description = "Uncracked Scarab Shell x 5",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 2846,
                        name = "Tiara of the Deep",
                        description = "Tiara of the Deep",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 2991,
                        name = "Nekrum's Medallion",
                        description = "Nekrum's Medallion",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
        },
    },

    -- Maraudon
    {
        complex = "Maraudon",
        dungeons = {
            {
                name = "Maraudon",
                levelRange = "46-55",
                quests = {
                    {
                        questId = 7044,
                        name = "Legends of Maraudon",
                        description = "Find a way to speak with Celebras. Requirements:, Celebrian Diamond, Celebrian Rod",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 7067,
                        name = "The Pariah's Instructions",
                        description = "Amulet of Union, Amulet of Spirits",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {
                            { questId = 7044, name = "Legends of Maraudon" },
                        },
                    },
                    {
                        questId = 7028,
                        name = "Twisted Evils",
                        description = "Theradric Crystal Carving x 15",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 7068,
                        name = "Shadowshard Fragments",
                        description = "Shadowshard Fragment x 10",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 7029,
                        name = "Vyletongue Corruption",
                        description = "Use the Filled Cerulean Vial on the Vylestem Vines to force the corrupted Noxxious Scion to emerge. Heal 8 plants by killing these Noxxious Scion, ...",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
        },
    },

    -- Sunken Temple
    {
        complex = "Sunken Temple",
        dungeons = {
            {
                name = "Temple of Atal'Hakkar",
                levelRange = "50-60",
                quests = {
                    {
                        questId = 1445,
                        name = "The Temple of Atal'Hakkar",
                        description = "Fetish of Hakkar x 20",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 3446,
                        name = "Into the Depths",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 3528,
                        name = "The God Hakkar",
                        description = "Filled Egg of Hakkar, Essence of Hakkar",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {
                            { questId = 3446, name = "Into the Depths" },
                        },
                    },
                    {
                        questId = 3527,
                        name = "The Prophecy of Mosh'aru",
                        description = "First Mosh'aru Tablet, Second Mosh'aru Tablet",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 4787,
                        name = "The Ancient Egg",
                        description = "Ancient Egg",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 3447,
                        name = "Secret of the Circle",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
        },
    },

    -- Blackrock Mountain
    {
        complex = "Blackrock Mountain",
        dungeons = {
            {
                name = "Blackrock Depths",
                levelRange = "52-60",
                quests = {
                    {
                        questId = 4241,
                        name = "Marshal Windsor",
                        description = "You recall Ragged John talking about Windsor being dragged off to a prison.",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 4242,
                        name = "Abandoned Hope",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {
                            { questId = 4241, name = "Marshal Windsor" },
                        },
                    },
                    {
                        questId = 4264,
                        name = "A Crumpled Up Note",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 4024,
                        name = "A Taste of Flame",
                        description = "You only know that the giant resides inside Blackrock Depths. Remember to use the Altered Black Dragonflight Molt on Bael'Gar's remains to capture ...",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 4123,
                        name = "The Heart of the Mountain",
                        description = "The Heart of the Mountain",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 3911,
                        name = "The Last Element",
                        description = "Essence of the Elements x 10",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 3802,
                        name = "Dark Iron Legacy",
                        description = "Ironfel",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 4126,
                        name = "Hurley Blackbreath",
                        description = "Lost Thunderbrew Recipe",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 4136,
                        name = "Ribbly Screwspigot",
                        description = "Ribbly's Head",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 4262,
                        name = "Overmaster Pyron",
                        description = "You recall Jalinda talking about Pyron guarding the quarry. Perhaps you should search there? Requirements:, Overmaster Pyron",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 4083,
                        name = "The Spectral Chalice",
                        description = "Star Ruby x 2, Gold Bar x 20, Truesilver Bar x 10",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 7848,
                        name = "Attunement to the Core",
                        description = "Core Fragment",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
            {
                name = "Lower Blackrock Spire",
                levelRange = "55-60",
                quests = {
                    {
                        questId = 4729,
                        name = "Kibler's Exotic Pets",
                        description = "Caged Worg Pup",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 4867,
                        name = "Urok Doomhowl",
                        description = "Warosh's Mojo",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 4743,
                        name = "Seal of Ascension",
                        description = "It is at that moment which you must place the Unforged Seal of Ascension before the great beast. You must then be quick to use the Orb of Draconic ...",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 4701,
                        name = "Put Her Down",
                        description = "Halycon",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 5081,
                        name = "Maxwell's Mission",
                        description = "War Master Voone, Highlord Omokk, Overlord Wyrmthalak",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
            {
                name = "Upper Blackrock Spire",
                levelRange = "55-60",
                quests = {
                    {
                        questId = 5102,
                        name = "General Drakkisath's Demise",
                        description = "General Drakkisath",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 5089,
                        name = "General Drakkisath's Command",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 4764,
                        name = "Doomrigger's Clasp",
                        description = "Doomrigger's Clasp",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 6502,
                        name = "Drakefire Amulet",
                        description = "Blood of the Black Dragon Champion",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
        },
    },

    -- Dire Maul
    {
        complex = "Dire Maul",
        dungeons = {
            {
                name = "Dire Maul: East",
                levelRange = "55-60",
                quests = {
                    {
                        questId = 7488,
                        name = "Lethtendris's Web",
                        description = "Lethtendris's Web",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 7441,
                        name = "Pusillin and the Elder Azj'Tordin",
                        description = "Return to Azj'Tordin at the Lariss Pavilion in Feralas should you recover the Book of Incantations. Requirements:, Book of Incantations",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 1193,
                        name = "A Broken Trap",
                        description = "Clearly, it would seem fortuitous that very few ogres know how to read. Clearly. Requirements:, Thorium Widget, Frost Oil",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
            {
                name = "Dire Maul: West",
                levelRange = "55-60",
                quests = {
                    {
                        questId = 7461,
                        name = "The Madness Within",
                        description = "Enter the Prison of Immol'thar and eradicate the foul demon that stands at its heart. Finally, confront Prince Tortheldrin in Athenaeum. Return to ...",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 7877,
                        name = "The Treasure of the Shen'dralar",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {
                            { questId = 7461, name = "The Madness Within" },
                        },
                    },
                },
            },
            {
                name = "Dire Maul: North",
                levelRange = "55-60",
                quests = {
                    {
                        questId = 5518,
                        name = "The Gordok Ogre Suit",
                        description = "Bolt of Runecloth x 4, Rugged Leather x 8, Rune Thread x 2, Ogre Tannin",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 5525,
                        name = "Free Knot!",
                        description = "What am I talking about, you have it already, don't you?! Is that it there??! Requirements:, Gordok Shackle Key",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 7703,
                        name = "Unfinished Gordok Business",
                        description = "According to Kromcrush, the \"old timey story\" says that Tortheldrin, a \"creepy\" elf who called himself a prince, stole it from one of the Gordok ...",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
        },
    },

    -- Stratholme
    {
        complex = "Stratholme",
        dungeons = {
            {
                name = "Stratholme",
                levelRange = "58-60",
                quests = {
                    {
                        questId = 5848,
                        name = "Of Love and Family",
                        description = "Return the painting to Tirion Fordring. Requirements:, Of Love and Family",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 5251,
                        name = "The Archivist",
                        description = "Archivist Galford, Archive Burned",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 5122,
                        name = "The Medallion of Faith",
                        description = "Retrieve the medallion from Malor the Zealous",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 5243,
                        name = "Houses of the Holy",
                        description = "Stratholme Holy Water x 5",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 5214,
                        name = "The Great Ezra Grimm",
                        description = "Grimm's Premium Tobacco",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 5282,
                        name = "The Restless Souls",
                        description = "Free 15 Restless Souls and return to Egan. Requirements:, Souls Freed x 15",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
        },
    },

    -- Scholomance
    {
        complex = "Scholomance",
        dungeons = {
            {
                name = "Scholomance",
                levelRange = "58-60",
                quests = {
                    {
                        questId = 5382,
                        name = "Doctor Theolen Krastinov, the Butcher",
                        description = "Doctor Theolen Krastinov, Remains of Eva Sarkhoff Burned, Remains of Lucien Sarkhoff Burned",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 5529,
                        name = "Plagued Hatchlings",
                        description = "Plagued Hatchling x 20",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 5343,
                        name = "Barov Family Fortune",
                        description = "The Deed to Brill, The Deed to Caer Darrow, The Deed to Southshore, The Deed to Tarren Mill",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 5341,
                        name = "Barov Family Fortune",
                        description = "The Deed to Brill, The Deed to Caer Darrow, The Deed to Southshore, The Deed to Tarren Mill",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 5466,
                        name = "The Lich, Ras Frostwhisper",
                        description = "Human Head of Ras Frostwhisper",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 4771,
                        name = "Dawn's Gambit",
                        description = "Vectus, Place Dawn's Gambit",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
        },
    },

    -- ========================================================================
    -- TBC DUNGEONS
    -- ========================================================================

    -- Hellfire Citadel
    {
        complex = "Hellfire Citadel",
        dungeons = {
            {
                name = "Hellfire Ramparts",
                levelRange = "60-62",
                quests = {
                    {
                        questId = 9575,
                        name = "Weaken the Ramparts",
                        description = "Gargolmar's Hand, Omor's Hoof, Nazan's Head",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 9572,
                        name = "Weaken the Ramparts",
                        description = "Gargolmar's Hand, Omor's Hoof, Nazan's Head",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 9587,
                        name = "Dark Tidings",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 9588,
                        name = "Dark Tidings",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
            {
                name = "The Blood Furnace",
                levelRange = "61-63",
                quests = {
                    {
                        questId = 9589,
                        name = "The Blood is Life",
                        description = "Fel Orc Blood Vial x 10",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 9590,
                        name = "The Blood is Life",
                        description = "Fel Orc Blood Vial x 10",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 9607,
                        name = "Heart of Rage",
                        description = "Fully Investigate The Blood Furnace",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {
                            { questId = 9575, name = "Weaken the Ramparts" },
                        },
                    },
                    {
                        questId = 9608,
                        name = "Heart of Rage",
                        description = "Fully Investigate The Blood Furnace",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {
                            { questId = 9572, name = "Weaken the Ramparts" },
                        },
                    },
                },
            },
            {
                name = "The Shattered Halls",
                levelRange = "70",
                quests = {
                    {
                        questId = 10704,
                        name = "How to Break Into the Arcatraz",
                        description = "Top Shard of the Arcatraz Key, Bottom Shard of the Arcatraz Key",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 9493,
                        name = "Pride of the Fel Horde",
                        description = "Shattered Hand Legionnaire x 8, Shattered Hand Centurion x 4, Shattered Hand Champion x 4",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 9496,
                        name = "Pride of the Fel Horde",
                        description = "Shattered Hand Legionnaire x 8, Shattered Hand Centurion x 4, Shattered Hand Champion x 4",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 10754,
                        name = "Entry Into the Citadel",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 10762,
                        name = "Grand Master Dumphry",
                        faction = "Alliance",
                        heroic = false,
                        prerequisites = {
                            { questId = 10754, name = "Entry Into the Citadel" },
                        },
                    },
                    {
                        questId = 10755,
                        name = "Entry Into the Citadel",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 10756,
                        name = "Grand Master Rohok",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {
                            { questId = 10755, name = "Entry Into the Citadel" },
                        },
                    },
                    {
                        questId = 10670,
                        name = "Tear of the Earthmother",
                        description = "Tear of the Earthmother",
                        faction = "Horde",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 10884,
                        name = "Trial of the Naaru: Mercy",
                        description = "This quest must be completed in Heroic dungeon difficulty. Requirements:, Unused Axe of the Executioner",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
        },
    },

    -- Coilfang Reservoir
    {
        complex = "Coilfang Reservoir",
        dungeons = {
            {
                name = "The Slave Pens",
                levelRange = "62-64",
                quests = {
                    {
                        questId = 9738,
                        name = "Lost in Action",
                        description = "Earthbinder Rayge Discovered, Naturalist Bite Discovered, Weeder Greenthumb Discovered, Windcaller Claw Discovered",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
            {
                name = "The Underbog",
                levelRange = "63-65",
                quests = {
                    {
                        questId = 9717,
                        name = "Oh, It's On!",
                        description = "Underspore Frond",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 9715,
                        name = "Bring Me A Shrubbery!",
                        description = "Sanguine Hibiscus x 5",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 9719,
                        name = "Stalk the Stalker",
                        description = "Brain of the Black Stalker",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
            {
                name = "The Steamvault",
                levelRange = "70",
                quests = {
                    {
                        questId = 9764,
                        name = "Orders from Lady Vashj",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 9763,
                        name = "The Warlord's Hideout",
                        description = "Warlord Kalithresh",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 9248,
                        name = "A Humble Offering",
                        description = "Abyssal Scepter, Cenarion Circle:",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 10885,
                        name = "Trial of the Naaru: Strength",
                        description = "This quest must be completed in Heroic dungeon difficulty. Requirements:, Kalithresh's Trident, Murmur's Essence",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
        },
    },

    -- Auchindoun
    {
        complex = "Auchindoun",
        dungeons = {
            {
                name = "Mana-Tombs",
                levelRange = "64-66",
                quests = {
                    {
                        questId = 10216,
                        name = "Safety Is Job One",
                        description = "Once that's done, find the Ethereal Transporter in the chamber before Shaffar's and activate it. Requirements:, Ethereal Crypt Raider x 10, Nexus...",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 10165,
                        name = "Undercutting the Competition",
                        description = "Shaffar's Wrappings",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 10977,
                        name = "Stasis Chambers of the Mana-Tombs",
                        description = "This quest may only be completed on Heroic difficulty. Requirements:, Mana-Tombs Stasis Chamber Investigated",
                        faction = "Both",
                        heroic = true,
                        prerequisites = {},
                    },
                    {
                        questId = 11373,
                        name = "Wanted: Shaffar's Wondrous Pendant",
                        description = "This quest may only be completed on Heroic difficulty. Requirements:, Shaffar's Wondrous Amulet",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
            {
                name = "Auchenai Crypts",
                levelRange = "65-67",
                quests = {
                    {
                        questId = 11374,
                        name = "Wanted: The Exarch's Soul Gem",
                        description = "This quest may only be completed on Heroic difficulty. Requirements:, The Exarch's Soul Gem",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 10164,
                        name = "Everything Will Be Alright",
                        description = "Exarch Maladaar",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
            {
                name = "Sethekk Halls",
                levelRange = "67-69",
                quests = {
                    {
                        questId = 10097,
                        name = "Brother Against Brother",
                        description = "Darkweaver Syth, Free Lakka",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 10098,
                        name = "Terokk's Legacy",
                        description = "The Saga of Terokk, Terokk's Mask, Terokk's Quill",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
            {
                name = "Shadow Labyrinth",
                levelRange = "70",
                quests = {
                    {
                        questId = 10095,
                        name = "Into the Heart of the Labyrinth",
                        description = "Murmur",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 10178,
                        name = "Find Spy To'gun",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 10091,
                        name = "The Soul Devices",
                        description = "Soul Device x 5",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 9831,
                        name = "Entry Into Karazhan",
                        description = "First Key Fragment",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 10094,
                        name = "The Codex of Blood",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 10886,
                        name = "Trial of the Naaru: Tenacity",
                        description = "This quest must be completed in Heroic dungeon difficulty. Requirements:, Millhouse Manastorm Rescued",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
        },
    },

    -- Tempest Keep
    {
        complex = "Tempest Keep",
        dungeons = {
            {
                name = "The Mechanar",
                levelRange = "69-70",
                quests = {
                    {
                        questId = 10704,
                        name = "How to Break Into the Arcatraz",
                        description = "Top Shard of the Arcatraz Key, Bottom Shard of the Arcatraz Key",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 10665,
                        name = "Fresh from the Mechanar",
                        description = "Overcharged Manacell",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
            {
                name = "The Botanica",
                levelRange = "70",
                quests = {
                    {
                        questId = 10704,
                        name = "How to Break Into the Arcatraz",
                        description = "Top Shard of the Arcatraz Key, Bottom Shard of the Arcatraz Key",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
            {
                name = "The Arcatraz",
                levelRange = "70",
                quests = {
                    {
                        questId = 10882,
                        name = "Harbinger of Doom",
                        description = "Harbinger Skyriss",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 10705,
                        name = "Seer Udalo",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 10888,
                        name = "Trial of the Naaru: Magtheridon",
                        description = "Magtheridon",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
        },
    },

    -- Caverns of Time
    {
        complex = "Caverns of Time",
        dungeons = {
            {
                name = "Old Hillsbrad Foothills",
                levelRange = "66-68",
                quests = {
                    {
                        questId = 10283,
                        name = "Taretha's Diversion",
                        description = "Speak to Thrall in the basement prison of Durnholde Keep when you have the Internment Lodges Set Ablaze. Requirements:, Internment Lodges Set Ablaze",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 10284,
                        name = "Escape from Durnholde",
                        description = "Speak with Erozion in Old Hillsbrad should you complete this task. Requirements:, Thrall's Destiny Fulfilled",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {
                            { questId = 10283, name = "Taretha's Diversion" },
                        },
                    },
                    {
                        questId = 10285,
                        name = "Return to Andormu",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {
                            { questId = 10284, name = "Escape from Durnholde" },
                        },
                    },
                },
            },
            {
                name = "The Black Morass",
                levelRange = "70",
                quests = {
                    {
                        questId = 10297,
                        name = "The Opening of the Dark Portal",
                        description = "Return to Sa'at should you succeed in your task. Requirements:, The Dark Portal Opened",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {
                            { questId = 10285, name = "Return to Andormu" },
                        },
                    },
                    {
                        questId = 10298,
                        name = "Hero of the Brood",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {
                            { questId = 10297, name = "The Opening of the Dark Portal" },
                        },
                    },
                    {
                        questId = 9836,
                        name = "The Master's Touch",
                        description = "Master's Touch",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
        },
    },

    -- Magisters' Terrace
    {
        complex = "Magisters' Terrace",
        dungeons = {
            {
                name = "Magisters' Terrace",
                levelRange = "70",
                quests = {
                    {
                        questId = 11488,
                        name = "Magisters' Terrace",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 11490,
                        name = "The Scryer's Scryer",
                        description = "Scrying Orb Activated",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {
                            { questId = 11488, name = "Magisters' Terrace" },
                        },
                    },
                    {
                        questId = 11492,
                        name = "Hard to Kill",
                        description = "Head of Kael'thas",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 11496,
                        name = "The Sanctum Wards",
                        description = "Mana Remnants x 4, Energize a Crystal Ward",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                    {
                        questId = 11499,
                        name = "Wanted: The Signet Ring of Prince Kael'thas",
                        description = "This quest may only be completed at the Magisters' Terrace on Heroic difficulty. Requirements:, The Signet Ring of Prince Kael'thas",
                        faction = "Both",
                        heroic = false,
                        prerequisites = {},
                    },
                },
            },
        },
    },
}

-- Tab definitions: which complexes go in which tab
DungeonQuestTracker.TAB_DEFINITIONS = {
    {
        value = "summary",
        text = "Summary",
        complexes = {},
    },
    {
        value = "dungeons",
        text = "Dungeons",
        complexes = {
            "Ragefire Chasm",
            "Wailing Caverns",
            "The Deadmines",
            "Shadowfang Keep",
            "Blackfathom Deeps",
            "The Stockade",
            "Gnomeregan",
            "Scarlet Monastery",
            "Razorfen Kraul",
            "Razorfen Downs",
            "Uldaman",
            "Zul'Farrak",
            "Maraudon",
            "Sunken Temple",
            "Blackrock Mountain",
            "Dire Maul",
            "Stratholme",
            "Scholomance",
            "Hellfire Citadel",
            "Coilfang Reservoir",
            "Auchindoun",
            "Tempest Keep",
            "Caverns of Time",
            "Magisters' Terrace",
        },
    },
}
